databases:
  - name: JobRecorder
    plan: free
    databaseName: JobRecorder
    user: JobRecorder

services:
  - type: web
    name: JobRecorder
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: JobRecorder
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
