databases:
  - name: joblogr
    plan: free
    databaseName: joblogr
    user: joblogr
services:
  - type: web
    name: joblogr
    env: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # # we already created these two files for you
    startCommand: "./bin/render-start.sh"
    envVars: # this section sets some ENV variables needed by Render for deployment
      - key: SECRET_KEY_BASE
        formDatabase:
          name: joblogr
          property: connectionString
        generateValue: true
      - key: RAILS_MASTER_KEY
